[tool.poetry]
name = "fntypes"
version = "0.1.0-dev3"
description = ""
authors = ["timoniq"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
